/**
 * Embedded Web Pages for Relay Control
 * Waveshare RP2350-POE-ETH-8DI-8RO
 */

#ifndef _WEB_PAGES_H_
#define _WEB_PAGES_H_

// Main HTML page (minified)
const char HTML_PAGE[] =
"<!DOCTYPE html>"
"<html><head>"
"<meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
"<title>Relay Control</title>"
"<style>"
"*{margin:0;padding:0;box-sizing:border-box}"
"body{font-family:Arial,sans-serif;background:#f0f0f0;padding:20px}"
".container{max-width:1200px;margin:0 auto}"
"h1{text-align:center;color:#333;margin-bottom:30px}"
".controls{text-align:center;margin-bottom:30px}"
".controls button{background:#007bff;color:white;border:none;padding:12px 30px;margin:0 10px;border-radius:5px;cursor:pointer;font-size:16px}"
".controls button:hover{background:#0056b3}"
".controls button.danger{background:#dc3545}"
".controls button.danger:hover{background:#c82333}"
".relay-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:20px}"
".relay-card{background:white;border-radius:10px;padding:20px;box-shadow:0 2px 5px rgba(0,0,0,0.1)}"
".relay-card h3{margin-bottom:15px;color:#333}"
".status{padding:10px;border-radius:5px;text-align:center;font-weight:bold;margin-bottom:15px}"
".status.on{background:#28a745;color:white}"
".status.off{background:#6c757d;color:white}"
".buttons{display:flex;gap:10px}"
".buttons button{flex:1;padding:10px;border:none;border-radius:5px;cursor:pointer;font-size:14px}"
".buttons button:first-child{background:#28a745;color:white}"
".buttons button:first-child:hover{background:#218838}"
".buttons button:last-child{background:#dc3545;color:white}"
".buttons button:last-child:hover{background:#c82333}"
".footer{text-align:center;margin-top:30px;color:#666}"
"</style>"
"</head><body>"
"<div class=\"container\">"
"<h1>Relay Control Panel</h1>"
"<div class=\"controls\">"
"<button onclick=\"allOn()\">All ON</button>"
"<button class=\"danger\" onclick=\"allOff()\">All OFF</button>"
"<button onclick=\"refresh()\">Refresh</button>"
"</div>"
"<div class=\"relay-grid\" id=\"relays\"></div>"
"<div class=\"footer\"><p>Waveshare RP2350-POE-ETH-8DI-8RO</p><p>IP: 192.168.1.100</p></div>"
"</div>"
"<script>"
"async function setRelay(relay,state){"
"try{"
"const r=await fetch(`/api/relay/${relay}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:state})});"
"const d=await r.json();"
"if(d.success)updateStatus(relay,state);"
"}catch(e){console.error('Error:',e);alert('Failed to control relay');}"
"}"
"async function allOn(){"
"try{"
"const r=await fetch('/api/relays/all/on',{method:'POST'});"
"const d=await r.json();"
"if(d.success)refresh();"
"}catch(e){console.error('Error:',e);}"
"}"
"async function allOff(){"
"try{"
"const r=await fetch('/api/relays/all/off',{method:'POST'});"
"const d=await r.json();"
"if(d.success)refresh();"
"}catch(e){console.error('Error:',e);}"
"}"
"function updateStatus(relay,state){"
"const el=document.getElementById(`status-${relay}`);"
"el.textContent=state?'ON':'OFF';"
"el.className='status '+(state?'on':'off');"
"}"
"async function loadRelays(){"
"try{"
"const r=await fetch('/api/relays');"
"const relays=await r.json();"
"const grid=document.getElementById('relays');"
"grid.innerHTML='';"
"for(let i=1;i<=8;i++){"
"const relay=relays[`relay_${i}`];"
"const card=document.createElement('div');"
"card.className='relay-card';"
"card.innerHTML=`<h3>Relay ${i}</h3>`+"
"`<div class=\"status ${relay.state?'on':'off'}\" id=\"status-${i}\">${relay.state?'ON':'OFF'}</div>`+"
"`<div class=\"buttons\">`+"
"`<button onclick=\"setRelay(${i},1)\">Turn ON</button>`+"
"`<button onclick=\"setRelay(${i},0)\">Turn OFF</button>`+"
"`</div>`;"
"grid.appendChild(card);"
"}"
"}catch(e){console.error('Error loading relays:',e);}"
"}"
"function refresh(){location.reload();}"
"loadRelays();"
"setInterval(loadRelays,5000);"
"</script>"
"</body></html>";

#endif /* _WEB_PAGES_H_ */
